from config.constants import KEY_BACKGROUND, KEY_STD, KEY_VOCALS


AUDIO_SAMPLE_RATE = 16000

NORMALIZE_TARGET_DBFS = -20.0
NORMALIZE_LIMIT_DB = 24.0
NORMALIZE_WAV_SUBTYPE = "PCM_16"

NORMALIZE_INPUTS = [f"{KEY_STD}_{KEY_VOCALS}", f"{KEY_STD}_{KEY_BACKGROUND}"]
NORMALIZE_RAISE_ON_MISSING_INPUT = True


VAD_SMOOTHING_WINDOW = 400
VAD_ENERGY_REL_THRESHOLD = 0.3
VAD_EXPAND_PRE = 0.015
VAD_EXPAND_POST = 0.015
VAD_EXPAND_DELTA = 0.005
VAD_PAD_MS = 50

MIX_PRE_SILENCE = 0.05
MIX_POST_SILENCE = 0.05
MIX_SAME_SPEAKER_GAP = 0.05
